name: Build Android aab

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, nixos ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Android aab
      run: |
        nix build .#android-bundle --print-build-logs
        
    - name: Find aab file
      id: find-aab
      run: |
        aab_FILE=$(find result/bin -name "*.aab" | head -1)
        aab_NAME=$(basename "$aab_FILE")
        echo "aab-file=$aab_FILE" >> $GITHUB_OUTPUT
        echo "aab-name=$aab_NAME" >> $GITHUB_OUTPUT
        echo "Found aab: $aab_NAME"

    - name: Upload unsigned aab artifact
      uses: actions/upload-artifact@v4
      with:
        name: portal-android-aab-unsigned
        path: ${{ steps.find-aab.outputs.aab-file }}
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          **/*.log
          **/gradle-daemon-*.log
        retention-days: 7

  sign:
    runs-on: [ self-hosted, nixos ]

    needs: build
    if: github.event_name != 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download unsigned aab
      uses: actions/download-artifact@v4
      with:
        name: portal-android-aab-unsigned
        path: ./aab

    - name: Decode keystore
      run: |
        echo "${{ secrets.PORTAL_DEBUG_KEYSTORE }}" | base64 -d > portal-debug.keystore

    - name: Find aab file
      id: find-aab
      run: |
        aab_FILE=$(find ./aab -name "*.aab" | head -1)
        aab_NAME=$(basename "$aab_FILE")
        SIGNED_aab_NAME="${aab_NAME%.*}-signed.aab"
        echo "aab-file=$aab_FILE" >> $GITHUB_OUTPUT
        echo "aab-name=$aab_NAME" >> $GITHUB_OUTPUT
        echo "signed-aab-name=$SIGNED_aab_NAME" >> $GITHUB_OUTPUT
        echo "Found aab: $aab_NAME"

    - name: Sign aab
      env:
        KEYSTORE_PASSWORD: ${{ secrets.PORTAL_DEBUG_KEYSTORE_PASSWORD }}
      run: |
        nix run nixpkgs#apksigner -- sign \
          --ks portal-debug.keystore \
          --ks-pass env:KEYSTORE_PASSWORD \
          --min-sdk-version 23 \
          --max-sdk-version 35 \
          --v1-signing-enabled=true \
          --v2-signing-enabled=true \
          --v3-signing-enabled=true \
          --v4-signing-enabled=true \
          --out ${{ steps.find-aab.outputs.signed-aab-name }} \
          ${{ steps.find-aab.outputs.aab-file }}

    - name: Upload signed aab artifact
      uses: actions/upload-artifact@v4
      with:
        name: portal-android-aab-signed
        path: ${{ steps.find-aab.outputs.signed-aab-name }}
        retention-days: 30 